FROM confluentinc/cp-kafka-connect

COPY ./kafka-connect-influxdb-0.3.1-SNAPSHOT.jar /etc/kafka-connect/jars/kafka-connect-influxdb-0.3.1-SNAPSHOT.jar
COPY ./influxdb-java-2.7.jar /etc/kafka-connect/jars/influxdb-java-2.7.jar
COPY ./scala-logging-api_2.11-2.1.2.jar /etc/kafka-connect/jars/scala-logging-api_2.11-2.1.2.jar
COPY ./scala-logging-slf4j_2.11-2.1.2.jar /etc/kafka-connect/jars/scala-logging-slf4j_2.11-2.1.2.jar


RUN chmod 777 /etc/kafka-connect/jars/*.jar